theme: jekyll-theme-slate
markdown            : kramdown
highlighter         : rouge
description: "Eng da Coputação e programador"
author:
  name: Eduardo Sant'Ana
  email: eduardosantana1313@gmail.com
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  EduardoSantAna1313
